esphome:
  name: esphome-web-9dd449
  friendly_name: ESPHome CFX
  min_version: 2025.5.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  baud_rate: 115200 
  level: WARN
  
# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid 
  password: !secret wifi_password

web_server:
  version: 3
  local: true

external_components:
  - source: github://andrewbackway/esphome-gps-idf
    refresh: 1s

uart:
  id: uart_gps
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

nmea_gps:
  id: gps
  uart_id: uart_gps
  verbose_logging: true
  latitude:
    name: "GPS Latitude"
    unit_of_measurement: "°"
    accuracy_decimals: 6
  longitude:
    name: "GPS Longitude"
    unit_of_measurement: "°"
    accuracy_decimals: 6
  altitude:
    name: "GPS Altitude"
    unit_of_measurement: "m"
    accuracy_decimals: 1
  speed:
    name: "GPS Speed"
    unit_of_measurement: "km/h"
    accuracy_decimals: 1
  course:
    name: "GPS Course"
    unit_of_measurement: "°"
    accuracy_decimals: 1
  satellites:
    name: "GPS Satellites"
    accuracy_decimals: 0
  hdop:
    name: "GPS HDOP"
    accuracy_decimals: 2
  datetime:
    name: "GPS DateTime"
  fix_status:
    name: "GPS Fix Status"